### ISSUE TITLE
"Transform: Unique Lines" duplicates row following the selection

### ISSUE THREAD

**Issue by micek-petr** [d-akara/vscode-extension-transformer#47]
I select multiple lines leaving the cursor on the next line which is not part of the selection.
Then I run "Transform: Unique Lines" and the line on which the cursor was becomes duplicated.
It happens every time I launch the action.

**Comment by d-akara** [comment]
The operation works on all lines of the selection.  In this case, the selection extends to the next line, but it does not include the contents of that line.
So, the line gets included because it is part of the selection, then when the replace is done it is replacing the selection and not the lines of the selection.  So we get a duplicate.
Will include a fix with next update.

**Comment by d-akara** [comment]
So after actually trying to change this behavior, I've decided against it.
The reason is that it would just create another edge case where I can not know for sure if the beginning or ending line was not intended to be included if they are empty.

This is somewhat just a subtle nuance of how vscode behaves in that it is actually vscode that is not showing you what you have selected.  If you select multiple blank lines, vscode shows you those in the selection, but does not include the last line or beginning depending on the direction.  This is somewhat a visual error from vscodes representation of the selection.
If I were to make changes here, I think it may introduce some odd behaviors in other scenarios.

For now, just be aware that when creating a selection, it will include the lines where the cursor starts and cursor ends regardless if they are blank and the selection is highlighted by vscode.
